### ISSUE TITLE
How to call Blink.begin() with WIFI and my own WIFI connection functions?

### ISSUE THREAD

**Issue by bobhuang1** [blinker-iot/blinker-doc#1]
I have been using Blynk to develop IoT products and I would like to switch to Blinker. I looked at the doc, and here is what I would like to do:
1. Using ESP8266/ESP32 in WIFI mode and connect to WIFI using my own custom functions
2. Then once WIFI connection is established, Blink.begin(auth) and get authenticated against the Blinker server, note that the begin function should not specify the WIFI SSID and password since it's already connected.
3. Perform functions of the product.
Is that possible? Thanks!

**Comment by coloz** [comment]
sorry, i don't understand your requirements very well. I suggest reading and modifying the source code to implement it
